export const products = [
  {
    id: 1,
    name: "Roadster Men Black Printed Round Neck T-shirt",
    price: 899,
    description: "Black printed T-shirt, has a round neck, and short sleeves",
    category: "T-shirts",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/t/e/0/l-st-theboys-black-smartees-original-imagnrkefgpaycng.jpeg",
  },
  {
    id: 2,
    name: "Roadster Men Grey Melange Printed Round Neck T-shirt",
    price: 799,
    description: "Grey melange printed T-shirt, has a round neck, and short sleeves",
    category: "T-shirts",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/b/s/8/m-t410-pgwli-eyebogler-original-imagg9zwtszneujt.jpeg",
  },
  {
    id: 3,
    name: "Levi's Men White Graphic Print Round Neck T-shirt",
    price: 999,
    description: "White graphic print T-shirt, has a round neck, and short sleeves",
    category: "T-shirts",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/y/0/5/xxl-t325-pwwh-eyebogler-original-imaghjzyk3fnfyrm.jpeg",
  },
  {
    id: 4,
    name: "Urbano Fashion Men Blue Slim Fit Jeans",
    price: 1799,
    description: "Blue slim-fit jeans, has a button and zip closure, and five pockets",
    category: "Jeans",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/h/y/g/32-jeans-knighthood-original-imaggcf7qdgbngjs.jpeg",
  },
  {
    id: 5,
    name: "H&M Men Beige Slim Fit Chino Style Cotton Trousers",
    price: 2499,
    description: "Beige slim-fit chinos, has a button and zip closure, and four pockets",
    category: "Trousers",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/trouser/q/1/w/32-cyfor-a-cyphus-original-imag62cygfvks5bh-bb.jpeg",
  },
  {
    id: 6,
    name: "Campus Sutra Men Olive Green Solid Bomber Jacket",
    price: 3499,
    description: "Olive green bomber jacket, has a zip closure, and two pockets",
    category: "Jackets",
    image: "https://rukminim2.flixcart.com/image/832/832/l3xcr680/jacket/a/f/z/l-no-mnt-7014-montrez-original-imagexbrbw7gqnyf.jpeg",
  },
  {
    id: 7,
    name: "Roadster Men Blue Slim Fit Casual Shirt",
    price: 1299,
    description: "Blue slim-fit casual shirt, has a spread collar, and long sleeves",
    category: "Shirts",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/i/a/z/xl-st2-vebnor-original-imagp6jfhvhgnuyz.jpeg",
  },
  {
    id: 8,
    name: "H&M Men Black Solid Padded Jacket with Stand Collar",
    price: 3999,
    description: "Black padded jacket, has a zip closure, and two pockets",
    category: "Jackets",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/jacket/b/h/e/m-1-no-bblwj1001-babela-original-imagkxessbgje8gg.jpeg",
  }
];